name: commitlint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Commitlint
        uses: remarkablemark/commitlint@v2
        with:
          checkout: true
